### ISSUE TITLE
Level of testing, preferred libraries?

### ISSUE THREAD

**Issue by kanishka-azimi** [hvr/cabal-plan#2]
Would you rather have more unit or integration tests?
If unit tests, what is your preferred library or framework?

I know this is a small program, that hardly needs tests. I just find it interesting and want to be able to refactor quickly if I contribute more.

**Comment by hvr** [comment]
@kanishka-azimi I started writing up a response but it appears I forgot to actually submit it... the gist of it: I think it makes only sense at this point to unit-test the library component of this package. tasty/test-framework/hedgehog/quickcheck all may make sense, if you can think up sensible tests for them.
